### PR TITLE
[bugfix] set cookies and crumb

### PR DESCRIPTION
**Pull request by foxhound91**
Yahoo has updated their APIs, now cookies must be fetch from a different URL and some headers are mandatory

### CODE REVIEW

**Comment by sfuhrm** [comment]
Thanks for the PR! Can you please re-check? For me I still get a HTTP 401 from their server.

The CrumbManager is only used for a part of the calls:
* HistDividendsRequest
* HistQuotes2Request
* HistSplitsRequest

Even adding it to the other calls, it fails on my machine. The mechanism to extract the cookie returns an empty string as the cookie in `CrumbManager.setCookie()`.

Bildschirmfoto_2024-06-19_19-08-25
 
Can you please cross-check with your machine?

**Comment by foxhound91** [comment]
@sfuhrm please re-test, this should be fixed now

**Comment by sfuhrm** [comment]
Thanks for the refinement, but it's not yet getting better:

```
java.io.FileNotFoundException: https://fc.yahoo.com/

	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2055)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2050)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2049)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1619)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
	at yahoofinance.histquotes2.CrumbManager.setCookie(CrumbManager.java:67)
...
```

Can you please take back the change with the logback logger? It is in maven scope runtime while the slf4jsimple was in maven scope test. Test scope was ok, runtime scope conflicts with slf4j which is a facade abstracting concrete logging.

**Comment by foxhound91** [comment]
Logback logger changes reverted.

@sfuhrm Do you think we could add back just the `logback.xml` file to have an appropriate log format configuration?

**Comment by sfuhrm** [comment]
> Logback logger changes reverted.
> 
> @sfuhrm Do you think we could add back just the `logback.xml` file to have an appropriate log format configuration?

I'd prefer to keep the simple logging. I didn't understand the point in formatting so far, may be you can explain more?
I think slf4j simple is a good choice if you don't need much control.

**Comment by sfuhrm** [comment]
To me this looks now like all data works with 'real' Yahoo Finance.
Thank you very much, @foxhound91 , I'll merge this and release a new version to Maven Central.

**Pull request merged**
